/*!
 * \file
 * \brief file tg_font_text.h
 *
 * font text holds the general information about text
 * that is generated by TgFontTextGenerator
 *
 * Copyright of Timo Hannukkala. All rights reserved.
 *
 * \author Timo Hannukkala <timohannukkala@hotmail.com>
 */

#ifndef TG_FONT_TEXT_H
#define TG_FONT_TEXT_H

#include <vector>
#include <string>

struct TgFontInfo;

struct TgFontTextCharacterInfo
{
    uint32_t m_character;           /*!< character index */
    int32_t m_fontFileNameIndex;    /*!< character is drawed from this TgFontText's index, from m_listFontFileNames, -1 == ignored */

    float positionLeftX;            /*!< glyph X position, generated in TgCharacterPositions::generateTextCharacterPositioning */
    size_t m_characterInFontInfoIndex; /*!< glyph index in TgFontInfo, generated in TgCharacterPositions::generateTextCharacterPositioning */

    uint8_t m_textColorR;
    uint8_t m_textColorG;
    uint8_t m_textColorB;
};

class TgFontText
{
public:
    TgFontText();

    void setFontFileNames(const std::string &mainFontFile, const std::vector<std::string> &listFontFileNames);
    void addCharacter(uint32_t character, uint8_t r, uint8_t g, uint8_t b);
    void generateFontTextInfoGlyphs(float fontSize);

    size_t getCharacterCount();
    TgFontTextCharacterInfo *getCharacter(size_t i);
    TgFontInfo *getFontInfo(size_t i);

    std::vector<uint32_t> getCharactersByFontFileNameIndex(int32_t fontFileNameIndex);

    float getTextWidth();
    float getVisibleTopY();
    float getVisibleBottomY();

    float getFontHeight();

    void setTextWidth(float textWidth);
    void setVisibleTopY(float visibleTopY);
    void setVisibleBottomY(float visibleBottomY);
private:
    float m_textWidth;
    float m_visibleTopY;
    float m_visibleBottomY;

    std::vector<std::string>m_listFontFileNames;
    std::vector<TgFontTextCharacterInfo>m_listCharacter;
    std::vector<TgFontInfo *>m_listFontInfo;
};

#endif // TG_FONT_TEXT_H
